version: '3.8'

services:

  web:
    
    build: .
    ports: 
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: mydb
    depends_on:
      - db
 


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    
    volumes: 
      - pgdata:/var/lib/postgresql/data

   
volumes:

   pgdata:
